site_name: Netlify Documentation
site_description: Netlify builds, deploys and hosts your front end projects
theme_dir: readthedocs/
repo_url: https://github.com/netlify/docs
pages:
  - ['index.md', 'Home']
  - ['cli.md', 'Command Line']
  - ['custom_domains.md', 'Custom Domains']
